#!/usr/bin/python                                                               

import matplotlib.pyplot as plt
import os, sys
import re
import math

##########################################################################  

try:
    os.environ["DISPLAY"]
except KeyError:
    print('Probleme avec l\'environnement')
    sys.exit(1);

##########################################################################     

if len (sys.argv) != 3 :
    print('Vous devez rentrer 2 arguments')
    sys.exit(1)

########################################################################## 

if len (sys.argv) == 3:
    try:
        float(sys.argv[1])
        int(sys.argv[2])
    except:
        print('Votre 1er argument doit etre un nombre decimal')
        print('Votre 2eme argument doit etre un entier naturel')
        sys.exit(1)
    a = float(sys.argv[1])
    if a <= 2:
        print('votre 1er argument doit etre au minimum de 2')
        sys.exit(1)
    nmax = int(sys.argv[2])
    if nmax < 0:
        print('Votre 2eme argument doit etre positif')
        sys.exit(1)
    x = -2
    list_one = []
    list_two = []
    while x < 2:
        k = 0
        calc = 0
        while k <= nmax:
            try:
                calc = calc + (math.cos(a ** k * math.pi * x)) / 2 ** k
                k = k + 1
            except:
                print("Error : Overflow")
                sys.exit(1);
        list_one.append(calc)
        list_two.append(x)
        x = x + 0.0001
    plt.plot(list_two, list_one, "g", label = 'a=' + str(a) + " ; nmax=" + str(nmax))
    plt.title("108monstre")
    plt.grid(1)
    plt.legend(loc=0)
    plt.show()
